---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: existing-vpc-cluster-1
  region: ap-south-1

vpc:
  id: "vpc-083dcf7003c9f40c0"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      ap-south-1a:
        id: "subnet-0093d5b4c773e0c44"
        cidr: "10.0.1.0/24" # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    #privateNetworking: true # if only 'Private' subnets are given, this must be enabled
